spring:
  datasource:
    url: jdbc:mariadb://doyoueat.c5aisrsakolc.ap-northeast-2.rds.amazonaws.com/fifaHasu
    username: doyoueat
    password: doyoueat96
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
